/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package Presentacion;

import claseConectar.conexion;
import java.awt.JobAttributes;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vitela
 */
public class frmConsultaProductosV extends javax.swing.JInternalFrame {
    DefaultTableModel tabla;
    

    /** Creates new form Productos */
    public frmConsultaProductosV() {
        initComponents();
        
        
      
        cargarlistaproductos("");
        
    }
     String comparar(String cod)
             //comprando stock  obtengo lo que hay en stock campo 5 y envio 
    {
        String cant="";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM producto_final WHERE id_producto='"+cod+"'");
            while(rs.next())
            {
                cant=rs.getString(5);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(frmConsultaProductosV.class.getName()).log(Level.SEVERE, null, ex);
        }
        return cant;
        
    }
  
    void cargarlistaproductos(String dato){
        String [] Titulo = {"Id de producto","categoria","Nombre","Descripcion","Precio"};
        tabla=new DefaultTableModel(null,Titulo);
    String []Registro= new String[5];
    String mostrar="SELECT * FROM producto_final WHERE CONCAT (id_producto,categoria,descripcion_producto,nombre_producto, precio_producto) LIKE '%"+dato+"%'"; 
    Statement st;
    
        try {
            st = cn.createStatement();
            ResultSet rs =st.executeQuery(mostrar);
            while(rs.next())
            {
                Registro[0]=rs.getString("id_producto");
                Registro[1]=rs.getString("categoria");
                Registro[2]=rs.getString("nombre_producto");
                Registro[3]=rs.getString("descripcion_producto");
                Registro[4]=rs.getString("precio_producto");
                
                tabla.addRow(Registro);
            }
            tablaProd.setModel(tabla);
        } catch (SQLException ex) {
            Logger.getLogger(frmConsultaProductosV.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnenviarpro = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();
        txtprod = new javax.swing.JTextField();
        lblBuscarProducto = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mnenviarpro.setText("Enviar a Factura");
        mnenviarpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnenviarproActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnenviarpro);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Productos");

        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaProd.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(tablaProd);

        txtprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodActionPerformed(evt);
            }
        });
        txtprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprodKeyReleased(evt);
            }
        });

        lblBuscarProducto.setText("Buscar Productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblBuscarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(txtprod, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarProducto)
                    .addComponent(txtprod, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtprodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodKeyReleased
// TODO add your handling code here:
    cargarlistaproductos(txtprod.getText());
}//GEN-LAST:event_txtprodKeyReleased

private void mnenviarproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnenviarproActionPerformed
// TODO add your handling code here: Validaciones enviar productos
   
    try {
        
         DefaultTableModel tabladet = (DefaultTableModel) frmVenta.tablaRealizarVenta.getModel();
         String[]  dato=new String[5];
   
         int  fila = tablaProd.getSelectedRow();
       
         if(fila==-1)
         {
             JOptionPane.showMessageDialog(null, "No  ha seleccionado ningun registro");
         }
         
         else
          {
          String codins=tablaProd.getValueAt(fila, 0).toString();
          String nombreins=tablaProd.getValueAt(fila, 2).toString();
         
          String precioins=tablaProd.getValueAt(fila, 4).toString();
          int c=0;
          int j=0;
           String  cant=JOptionPane.showInputDialog("ingrese cantidad");
              try {
                  Integer.parseInt(cant);
              } catch (NumberFormatException e) {
                  JOptionPane.showMessageDialog(this, "Debe ingresar sólo valores numéricos");
              }
         if((cant.equals("0")) || (cant.contains("-")))
         {
             JOptionPane.showMessageDialog(this, "Debe ingresar algun valor mayor que 0");
         }
         else
         {
             //igual a la cantidad solicitada.
             int canting=Integer.parseInt(cant);
             //recibo lo que hay en sotck
             int comp=Integer.parseInt(comparar(codins));
             if(canting>comp)
             {
                 JOptionPane.showMessageDialog(this,"Ud. no cuenta con el stock apropiado");
             }
             else
             {
                      for(int i=0;i<frmVenta.tablaRealizarVenta.getRowCount();i++)
          {
            Object com=frmVenta.tablaRealizarVenta.getValueAt(i,0);
            if(codins.equals(com))
            {
                j=i;
                frmVenta.tablaRealizarVenta.setValueAt(cant, i, 4);
                c=c+1;
       
            }
   
          }
          if(c==0)
          {
           
            
      
            dato[0]=codins;
            dato[1]=nombreins;
           // dato[2]=descripcionins;
            dato[2]=precioins;
            dato[3]=cant;
            //int x=(((Integer.parseInt(precioins))*(Integer.parseInt(cant))));
            dato[4]=""+(((Integer.parseInt(precioins))*(Integer.parseInt(cant))));
            
            tabladet.addRow(dato);
        
            frmVenta.tablaRealizarVenta.setModel(tabladet);
            
            
        }
             }
              
         }
        
    }
      
    
    } catch (Exception e) {
    }
    
}//GEN-LAST:event_mnenviarproActionPerformed

    private void txtprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBuscarProducto;
    private javax.swing.JMenuItem mnenviarpro;
    private javax.swing.JTable tablaProd;
    private javax.swing.JTextField txtprod;
    // End of variables declaration//GEN-END:variables
conexion cc= new conexion();
Connection cn = cc.conectar();

}
