
package Presentacion;

import claseConectar.conexion;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.*;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vitela
 */
public class frmConsultasVentas extends javax.swing.JInternalFrame {

    /** Creates new form ConsultasFacturas */
    public frmConsultasVentas() {
        initComponents();
        cargartodasfacturas();
        this.setLocation(25,15 );
        dchVenta.setEnabled(false);
       
    }
    void cargartodasfacturas()
    {
        DefaultTableModel tabla= new DefaultTableModel();
        String []titulos={"ID de venta","Id usuario","SUBTOTAL","IVA","TOTAL","FECHA"};
        tabla.setColumnIdentifiers(titulos);
        this.tablaVentas.setModel(tabla);
        String consulta= "SELECT * FROM venta";
        String []Datos= new String [7];
        try {
            Statement st = cn.createStatement();
            ResultSet rs= st.executeQuery(consulta);
            while(rs.next())
            {
                Datos[0]=rs.getString("id_venta");
                Datos[1]=rs.getString("id_usuario");
               
                Datos[2]=rs.getString("subtotal_venta");
                Datos[3]=rs.getString("iva_venta");
                Datos[4]=rs.getString("total_venta");
                Datos[5]=rs.getString("fecha_venta");
                
                tabla.addRow(Datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmConsultasProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnver = new javax.swing.JMenuItem();
        mneliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        rdbnnumero = new javax.swing.JRadioButton();
        rdbbnfecha = new javax.swing.JRadioButton();
        rdtnTodos = new javax.swing.JRadioButton();
        txtId = new javax.swing.JTextField();
        btnbuscador = new javax.swing.JButton();
        dchVenta = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        btnVentasDetalle = new javax.swing.JButton();

        mnver.setText("Ver Detalle");
        mnver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnverActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnver);

        mneliminar.setText("Eliminar");
        mneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mneliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mneliminar);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Ventas");

        buttonGroup1.add(rdbnnumero);
        rdbnnumero.setSelected(true);
        rdbnnumero.setText("Mostrar  por ID de venta:");
        rdbnnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbnnumeroActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbbnfecha);
        rdbbnfecha.setText("Mostrar por Fecha");
        rdbbnfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbbnfechaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdtnTodos);
        rdtnTodos.setText("Mostrar todas:");
        rdtnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdtnTodosActionPerformed(evt);
            }
        });

        btnbuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/buscar.png"))); // NOI18N
        btnbuscador.setText("BUSCAR");
        btnbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdbbnfecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdtnTodos)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdbnnumero)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dchVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbnnumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdbbnfecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdtnTodos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dchVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscador))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaVentas.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tablaVentas);

        btnVentasDetalle.setText("Venta a detalle");
        btnVentasDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasDetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVentasDetalle))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentasDetalle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setBounds(0, 0, 674, 308);
    }// </editor-fold>//GEN-END:initComponents

private void btnbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscadorActionPerformed
// TODO add your handling code here:
    
      
    
    String num=txtId.getText();
    
    String consulta="";
    if(rdbnnumero.isSelected()==true)
    {
        consulta= "SELECT * FROM venta WHERE id_venta='"+num+"'";
    }
    if(rdbbnfecha.isSelected()==true)
    {
           Date fecha=dchVenta.getDate();
   SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/YYYY");
String fec=""+formatofecha.format(fecha);
        consulta= "SELECT * FROM venta WHERE fecha_venta='"+fec+"'";
    }
    if(rdtnTodos.isSelected()==true)
    {
        consulta= "SELECT * FROM venta ";
    }
        DefaultTableModel tabla= new DefaultTableModel();
        String []titulos={"ID de venta","Id usuario","SUBTOTAL","IVA","TOTAL","FECHA"};
        tabla.setColumnIdentifiers(titulos);
        this.tablaVentas.setModel(tabla);
        
        String []Datos= new String [7];
        try {
            Statement st = cn.createStatement();
            ResultSet rs= st.executeQuery(consulta);
            while(rs.next())
            {
                Datos[0]=rs.getString("id_venta");
                Datos[1]=rs.getString("id_usuario");
               // Datos[2]=rs.getString("nombre_usuario");
                Datos[2]=rs.getString("subtotal_venta");
                Datos[3]=rs.getString("iva_venta");
                Datos[4]=rs.getString("total_venta");
                Datos[5]=rs.getString("fecha_venta");
                
                tabla.addRow(Datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmConsultasProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
   
   
    
}//GEN-LAST:event_btnbuscadorActionPerformed

private void rdbnnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbnnumeroActionPerformed
// TODO add your handling code here:
    if(rdbnnumero.isSelected()==true)
    {
        txtId.setEnabled(true);
        txtId.requestFocus();
        dchVenta.setDate(null);
        dchVenta.setEnabled(false);
        
        
    }
}//GEN-LAST:event_rdbnnumeroActionPerformed

private void rdbbnfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbbnfechaActionPerformed
// TODO add your handling code here:
    if(rdbbnfecha.isSelected()==true)
    {
        dchVenta.setEnabled(true);
        txtId.setEnabled(false);
        txtId.setText("");
        
    }
}//GEN-LAST:event_rdbbnfechaActionPerformed

private void rdtnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdtnTodosActionPerformed
// TODO add your handling code here:
    if(rdtnTodos.isSelected()==true)
    {
        dchVenta.setEnabled(false);
        dchVenta.setDate(null);
        txtId.setText("");
        txtId.setEnabled(false);
        cargartodasfacturas();
    }
    
    
}//GEN-LAST:event_rdtnTodosActionPerformed

private void mnverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnverActionPerformed
// TODO add your handling code here:
//    int filasele= tbfacturas.getSelectedRow();
//    if(filasele==-1)
//    {
//        JOptionPane.showMessageDialog(null, "No Seleciono ninguna fila");
//    }
//    else
//    {
//           DetalleVenta detalle = new DetalleVenta();
//    Principal.jdpescritorio.add(detalle);
//    detalle.toFront();
//    detalle.setVisible(true);
//        String numfac=tbfacturas.getValueAt(filasele, 0).toString();
//        String cod=tbfacturas.getValueAt(filasele, 1).toString();
//        //String ruc=tbfacturas.getValueAt(filasele, 2).toString();
//        String subtotal=tbfacturas.getValueAt(filasele, 3).toString();
//        String igv=tbfacturas.getValueAt(filasele, 4).toString();
//        String total=tbfacturas.getValueAt(filasele, 5).toString();
//        String fecha=tbfacturas.getValueAt(filasele, 6).toString();
//        DetalleVenta.txtfac.setText(numfac);
//        DetalleVenta.txtcod.setText(cod);
//       // DetalleVenta.txtruc.setText(ruc);
//        DetalleVenta.txtsub.setText(subtotal);
//        DetalleVenta.txtigv.setText(igv);
//        DetalleVenta.txttot.setText(total);
//        DetalleVenta.txtfecha.setText(fecha);
//        DefaultTableModel model = (DefaultTableModel) DetalleVenta.tbdetalle.getModel();
//        String ver="SELECT * FROM detallefactura WHERE num_fac='"+numfac+"'";
//        String []datos= new String[5]   ;
//        try {
//                Statement st = cn.createStatement();
//                ResultSet rs= st.executeQuery(ver);
//                while(rs.next())
//                {
//                    datos[0]=rs.getString("cod_pro");
//                    datos[1]=rs.getString("des_pro");
//                    datos[2]=rs.getString("cant_pro");
//                    datos[3]=rs.getString("pre_unit");
//                    datos[4]=rs.getString("pre_tot");
//                    model.addRow(datos);
//                    
//                }
//                DetalleVenta.tbdetalle.setModel(model);
//            } catch (SQLException ex) {
//                Logger.getLogger(ConsultasVentas.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        
//        
//        
//        
//        
//  
//    }
}//GEN-LAST:event_mnverActionPerformed

private void mneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mneliminarActionPerformed
//// TODO add your handling code here:
//        int fila=tbfacturas.getSelectedRow();
//    if(fila>=0)
//    {
//        String cod=tbfacturas.getValueAt(fila, 0).toString();
//            try {
//                PreparedStatement pst = cn.prepareStatement("DELETE FROM factura WHERE num_fac='"+cod+"'");
//                pst.executeUpdate();
//            } catch (SQLException ex) {
//                Logger.getLogger(ConsultasBoletas.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            cargartodasfacturas();
//        
//    }
//    else
//    {
//        JOptionPane.showMessageDialog(this, "Seleccione alguna fila");
//    }
}//GEN-LAST:event_mneliminarActionPerformed

    private void btnVentasDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasDetalleActionPerformed
        // TODO add your handling code here:
          try {
          frmDetalleVenta frmCV= new frmDetalleVenta();
    frmInicio.jMenuPantallaInicio.add(frmCV);
    frmCV.toFront();
    frmCV.setVisible(true);
        
    } catch (Exception e) {
    }
    }//GEN-LAST:event_btnVentasDetalleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVentasDetalle;
    private javax.swing.JButton btnbuscador;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dchVenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mneliminar;
    private javax.swing.JMenuItem mnver;
    private javax.swing.JRadioButton rdbbnfecha;
    private javax.swing.JRadioButton rdbnnumero;
    private javax.swing.JRadioButton rdtnTodos;
    public static javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
conexion cc= new conexion();
Connection cn= cc.conectar();

}
