/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Dusuario;
import Logica.Lusuario;
import Reportes.Reportes;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author vitela
 */
public class frmUsuario extends javax.swing.JInternalFrame {

    /**
   
     */
    public frmUsuario() {
        initComponents();
        MostrarUsuariosI("");
        InhabilitarComponentes();
        lblUsuarios.setVisible(false);
    }
    private String accion = "guardar";

    void OcultarColumnas() {
        tablaUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
        tablaUsuarios.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    void InhabilitarComponentes() {

        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnEliminar.setEnabled(false);
        
        txtidusuario.setText("");
        txtnombreu.setText("");
        txtApellidopu.setText("");
        txtApellidomu.setText("");
        txtTelefonou.setText("");
        txtDireccionu.setText("");
        txtEmailu.setText("");
        txtpContrasenau.setText("");
        
        txtidusuario.setVisible(false);
        txtnombreu.setEnabled(false);
        txtApellidopu.setEnabled(false);
        txtApellidomu.setEnabled(false);
        txtTelefonou.setEnabled(false);
        txtDireccionu.setEnabled(false);
        cboPuesto.setEnabled(false);
        txtEmailu.setEnabled(false);
        txtpContrasenau.setEnabled(false);

    }

    void HabilitarComponentes() {
        txtidusuario.setVisible(false);
        txtnombreu.setEnabled(true);
        txtApellidopu.setEnabled(true);
        txtApellidomu.setEnabled(true);
        txtTelefonou.setEnabled(true);
        txtDireccionu.setEnabled(true);
        cboPuesto.setEnabled(true);
        txtEmailu.setEnabled(true);
        txtpContrasenau.setEnabled(true);
        
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnEliminar.setEnabled(true);

        txtidusuario.setText("");
        txtnombreu.setText("");
        txtApellidopu.setText("");
        txtApellidomu.setText("");
        txtTelefonou.setText("");
        txtDireccionu.setText("");
        txtEmailu.setText("");
        txtpContrasenau.setText("");
    }

    void MostrarUsuariosI(String buscar) {
        try {
            DefaultTableModel modelo;
            Lusuario func = new Lusuario();
            modelo = func.MostrarUsuarios(buscar);

            tablaUsuarios.setModel(modelo);
            OcultarColumnas();
            lbltotalRegistros.setText("Total registros" + Integer.toString(func.totalregistros));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuarios = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtidusuario = new javax.swing.JTextField();
        lblNom = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblContra = new javax.swing.JLabel();
        txtDireccionu = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblAPaterno = new javax.swing.JLabel();
        lblApellidom = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblPuesto = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtTelefonou = new javax.swing.JTextField();
        txtApellidomu = new javax.swing.JTextField();
        txtApellidopu = new javax.swing.JTextField();
        txtEmailu = new javax.swing.JTextField();
        txtnombreu = new javax.swing.JTextField();
        txtpContrasenau = new javax.swing.JPasswordField();
        cboPuesto = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        lblBusNombre = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lbltotalRegistros = new javax.swing.JLabel();
        btnGenerarRep = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantener Usuarios");
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        lblUsuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuarios.setText("Usuarios");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Usuarios"));

        lblNom.setText("Nombre:");

        lblDireccion.setText("Dirección:");

        lblContra.setText("Contraseña:");

        txtDireccionu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionuActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(102, 102, 102));
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(102, 102, 102));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblAPaterno.setText("Apellido Paterno:");

        lblApellidom.setText("Apellido Materno:");

        lblTel.setText("Teléfono:");

        lblPuesto.setText("Puesto:");

        lblEmail.setText("Email:");

        txtTelefonou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonouActionPerformed(evt);
            }
        });
        txtTelefonou.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonouKeyTyped(evt);
            }
        });

        txtApellidomu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidomuActionPerformed(evt);
            }
        });
        txtApellidomu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidomuKeyTyped(evt);
            }
        });

        txtApellidopu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidopuActionPerformed(evt);
            }
        });
        txtApellidopu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidopuKeyTyped(evt);
            }
        });

        txtEmailu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailuActionPerformed(evt);
            }
        });
        txtEmailu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailuKeyTyped(evt);
            }
        });

        txtnombreu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreuActionPerformed(evt);
            }
        });
        txtnombreu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreuKeyTyped(evt);
            }
        });

        cboPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propietaria", "Florista" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblTel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelefonou, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblApellidom)
                            .addGap(18, 18, 18)
                            .addComponent(txtApellidomu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAPaterno)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidopu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPuesto)
                            .addComponent(lblEmail))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccionu, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNom)
                            .addComponent(lblDireccion)
                            .addComponent(lblContra))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtidusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombreu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(txtpContrasenau, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnNuevo)
                .addGap(102, 102, 102)
                .addComponent(btnGuardar)
                .addGap(82, 82, 82)
                .addComponent(btnCancelar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtidusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom)
                    .addComponent(txtnombreu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPaterno)
                    .addComponent(txtApellidopu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidom)
                    .addComponent(txtApellidomu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTel)
                    .addComponent(txtTelefonou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContra)
                    .addComponent(txtpContrasenau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros"));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaUsuarios);

        btnBuscar.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(102, 102, 102));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        lblBusNombre.setText("Buscar por nombre:");

        btnSalir.setBackground(new java.awt.Color(102, 102, 102));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lbltotalRegistros.setText("Registros");

        btnGenerarRep.setText("Generar Reporte");
        btnGenerarRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotalRegistros)
                .addGap(73, 73, 73))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalir))
                            .addComponent(lblBusNombre)
                            .addComponent(btnGenerarRep))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBusNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnEliminar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotalRegistros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarRep)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblUsuarios)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtnombreu.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar Nombre de Usuario");
            txtnombreu.requestFocus();
            return;
        }
        if (txtApellidopu.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar Apellido Paterno");
            txtApellidopu.requestFocus();
            return;
        }
         if (txtApellidomu.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar Apellido Materno");
            txtApellidomu.requestFocus();
            return;
        }
        if (txtTelefonou.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar Telefono");
            txtTelefonou.requestFocus();
            return;
        }

        if (txtDireccionu.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar Direccion");
            txtDireccionu.requestFocus();
            return;
        }

          if (txtEmailu.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar Email");
            txtEmailu.requestFocus();
            return;
        }
          
         if (txtpContrasenau.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar Contraseña");
            txtpContrasenau.requestFocus();
            return;
        }

        Dusuario dts = new Dusuario();
        Lusuario func = new Lusuario();

        dts.setNombreu(txtnombreu.getText());
        dts.setApellidopu(txtApellidopu.getText());
        dts.setApellidomu(txtApellidomu.getText());
        dts.setTelefonou(txtTelefonou.getText());
        dts.setDireccionu(txtDireccionu.getText());
        int seleccionado = cboPuesto.getSelectedIndex();
        dts.setPuestou((String) cboPuesto.getItemAt(seleccionado));
        dts.setEmailu(txtEmailu.getText());
        dts.setContrasenau(txtpContrasenau.getText());

        if (accion.equals("guardar")) {
            if (func.InsertarUsuario(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El usuario fue registrado con exito ");
                MostrarUsuariosI("");
                InhabilitarComponentes();
            }

        } else if (accion.equals("editar")) {
            dts.setIdusuario(Integer.parseInt(txtidusuario.getText()));

            if (func.EditarUsuario(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El registro de Usuario  fue editado con exito ");
                MostrarUsuariosI("");
                InhabilitarComponentes();
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        HabilitarComponentes();
        btnGuardar.setText("Guardar");
        accion = "guardar";
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        if (!txtidusuario.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de eliminar Usuario?", "Confirmar", 2);

            if (confirmacion == 0) {
                Lusuario func = new Lusuario();
                Dusuario dts = new Dusuario();

                dts.setIdusuario(Integer.parseInt(txtidusuario.getText()));
                func.EliminarUsuario(dts);
                MostrarUsuariosI("");
               InhabilitarComponentes();

            }

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        MostrarUsuariosI(txtBuscar.getText());

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtDireccionuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionuActionPerformed
        // TODO add your handling code here:
        txtDireccionu.transferFocus();
    }//GEN-LAST:event_txtDireccionuActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        btnGuardar.setText("Editar");
        HabilitarComponentes();
        btnEliminar.setEnabled(true);
        accion = "editar";

        int fila = tablaUsuarios.rowAtPoint(evt.getPoint());

        txtidusuario.setText(tablaUsuarios.getValueAt(fila, 0).toString());
        txtnombreu.setText(tablaUsuarios.getValueAt(fila, 1).toString());
        txtApellidopu.setText(tablaUsuarios.getValueAt(fila, 2).toString());
        txtApellidomu.setText(tablaUsuarios.getValueAt(fila, 3).toString());
        txtTelefonou.setText(tablaUsuarios.getValueAt(fila, 4).toString());
        txtDireccionu.setText(tablaUsuarios.getValueAt(fila, 5).toString());
        cboPuesto.setSelectedItem(tablaUsuarios.getValueAt(fila, 6).toString());
        txtEmailu.setText(tablaUsuarios.getValueAt(fila, 7).toString());
        txtpContrasenau.setText(tablaUsuarios.getValueAt(fila, 8).toString());
        


    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtTelefonouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonouActionPerformed
        // TODO add your handling code here:
        txtTelefonou.transferFocus();
    }//GEN-LAST:event_txtTelefonouActionPerformed

    private void txtApellidomuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidomuActionPerformed
        // TODO add your handling code here:
        txtApellidomu.transferFocus();
    }//GEN-LAST:event_txtApellidomuActionPerformed

    private void txtApellidopuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidopuActionPerformed
        // TODO add your handling code here:
        txtApellidopu.transferFocus();
    }//GEN-LAST:event_txtApellidopuActionPerformed

    private void txtEmailuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailuActionPerformed
        // TODO add your handling code here:
        txtEmailu.transferFocus();

    }//GEN-LAST:event_txtEmailuActionPerformed

    private void txtnombreuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreuActionPerformed
        // TODO add your handling code here:
        txtnombreu.transferFocus();
    }//GEN-LAST:event_txtnombreuActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        MostrarUsuariosI(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtnombreuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreuKeyTyped
        // TODO add your handling code here:
 String s1=String.valueOf(evt.getKeyChar());
        
        if(!(s1.matches("[\ba-zA-Záéóíú.ÁÉÍÓÚñÑ ]"))){
            evt.consume();
            getToolkit().beep();
             JOptionPane.showMessageDialog(this, "Ingrese letras");
            //Regresa cursor al campo 
            txtnombreu.setCursor(null);
            txtnombreu.setCaretColor(Color.red);
        }

    }//GEN-LAST:event_txtnombreuKeyTyped

    private void txtApellidopuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidopuKeyTyped
        // TODO add your handling code here:
           String s1=String.valueOf(evt.getKeyChar());
        
        if(!(s1.matches("[\ba-zA-Záéóíú.ÁÉÍÓÚñÑ ]"))){
            evt.consume();
            getToolkit().beep();
             JOptionPane.showMessageDialog(this, "Ingrese letras");
            //Regresa cursor al campo 
            txtApellidopu.setCursor(null);
            txtApellidopu.setCaretColor(Color.red);
        }
    }//GEN-LAST:event_txtApellidopuKeyTyped

    private void txtApellidomuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidomuKeyTyped
        // TODO add your handling code here:
        String s1=String.valueOf(evt.getKeyChar());
        
        if(!(s1.matches("[\ba-zA-Záéóíú.ÁÉÍÓÚñÑ ]"))){
            evt.consume();
            getToolkit().beep();
             JOptionPane.showMessageDialog(this, "Ingrese letras");
            //Regresa cursor al campo 
            txtApellidomu.setCursor(null);
            txtApellidomu.setCaretColor(Color.red);
        }
    }//GEN-LAST:event_txtApellidomuKeyTyped

    private void txtTelefonouKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonouKeyTyped
        // TODO add your handling code here:
         String s1=String.valueOf(evt.getKeyChar());
        
        if(!(s1.matches("[\b0-9-* ]"))){ 
            evt.consume();
            getToolkit().beep();
             JOptionPane.showMessageDialog(this, "Ingrese digitos");
            //Regresa cursor al campo 
            txtTelefonou.setCursor(null);
            txtTelefonou.setCaretColor(Color.red);
        }
    }//GEN-LAST:event_txtTelefonouKeyTyped

    private void btnGenerarRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRepActionPerformed
        // TODO add your handling code here:
        try{
            Reportes reporte=new Reportes();
            try {
                reporte.ReporteUsuario();
            } catch (SQLException ex) {
                Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }catch(JRException ex){
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarRepActionPerformed

    private void txtEmailuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailuKeyTyped
        // TODO add your handling code here:
//         String s1=String.valueOf(evt.getKeyChar());
//        
//        if(!(s1.matches("^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\\.[a-zA-Z]{2,4}$"))){ 
//            evt.consume();
//            getToolkit().beep();
//             JOptionPane.showMessageDialog(this, "error");
//            //Regresa cursor al campo 
//            txtEmailu.setCursor(null);
//            txtEmailu.setCaretColor(Color.red);
//        }
//       
    }//GEN-LAST:event_txtEmailuKeyTyped

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarRep;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboPuesto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAPaterno;
    private javax.swing.JLabel lblApellidom;
    private javax.swing.JLabel lblBusNombre;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lbltotalRegistros;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtApellidomu;
    private javax.swing.JTextField txtApellidopu;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDireccionu;
    private javax.swing.JTextField txtEmailu;
    private javax.swing.JTextField txtTelefonou;
    private javax.swing.JTextField txtidusuario;
    private javax.swing.JTextField txtnombreu;
    private javax.swing.JPasswordField txtpContrasenau;
    // End of variables declaration//GEN-END:variables
}
